apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: krapp-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krapp-puma
  template:
    metadata:
        name: krapp
        labels:
          app: krapp-puma
    spec:
      containers:
      - name: krapp
        image: manuraj/krapp:latest
        env:
        - name: 'RAILS_ENV'
          value: 'production'
        ports:
        - containerPort: 3000
